# Generated by Django 5.2 on 2025-04-29 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubestats',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='youtubestats',
            name='title',
        ),
        migrations.AddField(
            model_name='youtubestats',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialaccount'),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='subscriber_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='video_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='view_count',
            field=models.BigIntegerField(),
        ),
    ]
