# Generated by Django 5.2 on 2025-04-29 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_youtubestats_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubestats',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
