# Generated by Django 5.2 on 2025-05-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_twittercredential_twitterstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterstats',
            old_name='created_at',
            new_name='recorded_at',
        ),
    ]
