# Generated by Django 5.2 on 2025-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_created_at_twitterstats_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='subscriber_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
