# Generated by Django 5.2 on 2025-05-04 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_socialaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterstats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
