# Generated by Django 5.2 on 2025-05-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_twitterstats_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterstats',
            name='created_at',
        ),
    ]
