# Generated by Django 5.2 on 2025-05-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_twitterstats_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='InstagramCredential',
        ),
        migrations.DeleteModel(
            name='InstagramStats',
        ),
    ]
