# Generated by Django 5.2 on 2025-05-30 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_socialaccount_access_token_youtubecredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubestats',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
