# Generated by Django 5.2 on 2025-05-30 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_youtubestats_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercredential',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
