# Generated by Django 5.2 on 2025-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_twittercredential_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubestats',
            name='social_account',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='connected',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='platform',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='YoutubeCredential',
        ),
        migrations.DeleteModel(
            name='YouTubeStats',
        ),
    ]
